authorizeHttpRequests:
  permitAll: /auth/login,/auth/register,/swagger-ui/**,/v3/api-docs/**
  authenticated: /api/**,/auth/refresh/**
  denyAll: /users
cors:
  originPatterns: http://localhost:3000,http://localhost:8080,http://127.0.0.1:5500
security:
  jwt:
    token:
      secret-key: secret
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projeto_difm?useTimezone=true&serverTimezone=UTC&useSSL=false
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
springdoc:
  pathsToMatch:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true